name: Check

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      REACT_APP_BEE_HOSTS: 'https://gateway-proxy-bee-0-0.gateway.ethswarm.org/,https://gateway-proxy-bee-1-0.gateway.ethswarm.org/,https://gateway-proxy-bee-2-0.gateway.ethswarm.org/,https://gateway-proxy-bee-3-0.gateway.ethswarm.org/,https://gateway-proxy-bee-4-0.gateway.ethswarm.org/,https://gateway-proxy-bee-5-0.gateway.ethswarm.org/,https://gateway-proxy-bee-6-0.gateway.ethswarm.org/,https://gateway-proxy-bee-7-0.gateway.ethswarm.org/,https://gateway-proxy-bee-8-0.gateway.ethswarm.org/,https://gateway-proxy-bee-9-0.gateway.ethswarm.org/'

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      ## Try getting the node modules from cache, if failed npm ci
      - uses: actions/cache@v2
        id: cache-npm
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-${{ matrix.node-version }}-${{ env.cache-name }}-
            ${{ runner.OS }}-node-${{ matrix.node-version }}-

      - name: Install npm deps
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci

      - name: Commit linting
        uses: wagoid/commitlint-github-action@v2

      - name: Code linting
        run: npm run lint:check
        env:
          CI: true

      - name: Dependency check
        run: npm run depcheck

      - name: Update supported Bee action
        uses: ethersphere/update-supported-bee-action@v1
        if: github.ref == 'refs/heads/master'

      - name: Build
        run: npm run build

      - name: Create preview
        uses: ethersphere/beeload-action@v1
        continue-on-error: true
        with:
          bee-url: https://unlimited.gateway.ethswarm.org
          preview: 'true'
          token: ${{ secrets.REPO_GHA_PAT }}
          extra-params: '-H "${{ secrets.GATEWAY_AUTHORIZATION_HEADER }}"'

      - name: Upload to testnet
        uses: ethersphere/beeload-action@v1
        continue-on-error: true
        with:
          bee-url: https://api.gateway.testnet.ethswarm.org
